alias DTGDATE='date +%Y-%m-%d-%H%M%Z'
alias DTGSDATE='date +%Y-%m-%d-%H%M%S%Z'
alias list='ls -alh'
alias goexport='cd /var/cli_api_ops/export_import'
alias gougex='cd /var/upgrade_export'
alias goapi='cd /var/cli_api_ops'
alias goapiwip='cd /var/cli_api_ops.wip'
alias goexportwip='cd /var/cli_api_ops.wip/export_import'
